repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--chars," "]
    - id: check-merge-conflict



- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.14
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format

- repo: local
  hooks:
    - id: export-django-requirements
      name: Export Django requirements
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes --output infra/requirements.django.txt
      files: ^(pyproject.toml|poetry.lock)$

- repo: local
  hooks:
    - id: export-schema-openapi
      name: Export schema OpenAPI
      language: system
      pass_filenames: false
      entry: python backend/manage.py spectacular --file docs/schema.yml
      # files: (.py)$
      types: [python]


# TODO: интересное решение
# ci:
#     autofix_commit_msg: |
#         ci: auto fixes from pre-commit hooks

#         for more information, see https://pre-commit.ci
#     autofix_prs: false
#     autoupdate_commit_msg: 'ci: pre-commit autoupdate'
#     autoupdate_schedule: monthly
