version: '3.9'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/app/static/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
