version: '3.3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: 
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: 
      context: ../backend/
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    # command: cp -r /app/dist/. /frontend_static/
    volumes:
      - static:/app/result_build/
    # volumes:
    #   - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/dist:/usr/share/nginx/html/
      - static:/var/html/static/
 